import Country from '#models/country'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  static environment = ['development', 'test', 'production']

  async run() {
    const uniqueKey = `isoCode`

    await Country.updateOrCreateMany(uniqueKey, [
      { isoCode: `AF`, name: `Afghanistan`, nationality: `Afghan` },
      { isoCode: `AX`, name: `Aland Islands`, nationality: `Alandish` },
      { isoCode: `AL`, name: `Albania`, nationality: `Albanian` },
      { isoCode: `DZ`, name: `Algeria`, nationality: `Algerian` },
      { isoCode: `AS`, name: `American Samoa`, nationality: `American Samoan` },
      { isoCode: `AD`, name: `AndorrA`, nationality: `Andorran` },
      { isoCode: `AO`, name: `Angola`, nationality: `Angolan` },
      { isoCode: `AI`, name: `Anguilla`, nationality: `Anguillan` },
      { isoCode: `AQ`, name: `Antarctica`, nationality: `Antarctic` },
      { isoCode: `AG`, name: `Antigua and Barbuda`, nationality: `Antiguan or Barbudan` },
      { isoCode: `AR`, name: `Argentina`, nationality: `Argentine` },
      { isoCode: `AM`, name: `Armenia`, nationality: `Armenian` },
      { isoCode: `AW`, name: `Aruba`, nationality: `Aruban` },
      { isoCode: `AU`, name: `Australia`, nationality: `Australian` },
      { isoCode: `AT`, name: `Austria`, nationality: `Austrian` },
      { isoCode: `AZ`, name: `Azerbaijan`, nationality: `Azerbaijani` },
      { isoCode: `BS`, name: `Bahamas`, nationality: `Bahamian` },
      { isoCode: `BH`, name: `Bahrain`, nationality: `Bahraini` },
      { isoCode: `BD`, name: `Bangladesh`, nationality: `Bangladeshi` },
      { isoCode: `BB`, name: `Barbados`, nationality: `Barbadian` },
      { isoCode: `BY`, name: `Belarus`, nationality: `Belarusian` },
      { isoCode: `BE`, name: `Belgium`, nationality: `Belgian` },
      { isoCode: `BZ`, name: `Belize`, nationality: `Belizean` },
      { isoCode: `BJ`, name: `Benin`, nationality: `Beninese` },
      { isoCode: `BM`, name: `Bermuda`, nationality: `Bermudian` },
      { isoCode: `BT`, name: `Bhutan`, nationality: `Bhutanese` },
      { isoCode: `BO`, name: `Bolivia`, nationality: `Bolivian` },
      { isoCode: `BA`, name: `Bosnia and Herzegovina`, nationality: `Bosnian or Herzegovinian` },
      { isoCode: `BW`, name: `Botswana`, nationality: `Botswanan` },
      { isoCode: `BV`, name: `Bouvet Island`, nationality: `Bouvet Islander` },
      { isoCode: `BR`, name: `Brazil`, nationality: `Brazilian` },
      {
        isoCode: `IO`,
        name: `British Indian Ocean Territory`,
        nationality: `British Indian Ocean Territory Citizen`,
      },
      { isoCode: `BN`, name: `Brunei Darussalam`, nationality: `Bruneian` },
      { isoCode: `BG`, name: `Bulgaria`, nationality: `Bulgarian` },
      { isoCode: `BF`, name: `Burkina Faso`, nationality: `Burkinabe` },
      { isoCode: `BI`, name: `Burundi`, nationality: `Burundian` },
      { isoCode: `KH`, name: `Cambodia`, nationality: `Cambodian` },
      { isoCode: `CM`, name: `Cameroon`, nationality: `Cameroonian` },
      { isoCode: `CA`, name: `Canada`, nationality: `Canadian` },
      { isoCode: `CV`, name: `Cape Verde`, nationality: `Cape Verdean` },
      { isoCode: `KY`, name: `Cayman Islands`, nationality: `Caymanian` },
      { isoCode: `CF`, name: `Central African Republic`, nationality: `Central African` },
      { isoCode: `TD`, name: `Chad`, nationality: `Chadian` },
      { isoCode: `CL`, name: `Chile`, nationality: `Chilean` },
      { isoCode: `CN`, name: `China`, nationality: `Chinese` },
      { isoCode: `CX`, name: `Christmas Island`, nationality: `Christmas Islander` },
      { isoCode: `CC`, name: `Cocos (Keeling) Islands`, nationality: `Cocos Islander` },
      { isoCode: `CO`, name: `Colombia`, nationality: `Colombian` },
      { isoCode: `KM`, name: `Comoros`, nationality: `Comoran` },
      { isoCode: `CG`, name: `Congo`, nationality: `Congolese` },
      { isoCode: `CD`, name: `Congo, The Democratic Republic of the`, nationality: `Congolese` },
      { isoCode: `CK`, name: `Cook Islands`, nationality: `Cook Islander` },
      { isoCode: `CR`, name: `Costa Rica`, nationality: `Costa Rican` },
      { isoCode: `CI`, name: 'Cote D`Ivoire', nationality: `Ivorian` },
      { isoCode: `HR`, name: `Croatia`, nationality: `Croatian` },
      { isoCode: `CU`, name: `Cuba`, nationality: `Cuban` },
      { isoCode: `CY`, name: `Cyprus`, nationality: `Cypriot` },
      { isoCode: `CZ`, name: `Czech Republic`, nationality: `Czech` },
      { isoCode: `DK`, name: `Denmark`, nationality: `Danish` },
      { isoCode: `DJ`, name: `Djibouti`, nationality: `Djiboutian` },
      { isoCode: `DM`, name: `Dominica`, nationality: `Dominican` },
      { isoCode: `DO`, name: `Dominican Republic`, nationality: `Dominican` },
      { isoCode: `EC`, name: `Ecuador`, nationality: `Ecuadorian` },
      { isoCode: `EG`, name: `Egypt`, nationality: `Egyptian` },
      { isoCode: `SV`, name: `El Salvador`, nationality: `Salvadoran` },
      { isoCode: `GQ`, name: `Equatorial Guinea`, nationality: `Equatorial Guinean` },
      { isoCode: `ER`, name: `Eritrea`, nationality: `Eritrean` },
      { isoCode: `EE`, name: `Estonia`, nationality: `Estonian` },
      { isoCode: `ET`, name: `Ethiopia`, nationality: `Ethiopian` },
      { isoCode: `FK`, name: `Falkland Islands (Malvinas)`, nationality: `Falkland Islander` },
      { isoCode: `FO`, name: `Faroe Islands`, nationality: `Faroese` },
      { isoCode: `FJ`, name: `Fiji`, nationality: `Fijian` },
      { isoCode: `FI`, name: `Finland`, nationality: `Finnish` },
      { isoCode: `FR`, name: `France`, nationality: `French` },
      { isoCode: `GF`, name: `French Guiana`, nationality: `French Guianese` },
      { isoCode: `PF`, name: `French Polynesia`, nationality: `French Polynesian` },
      {
        isoCode: `TF`,
        name: `French Southern Territories`,
        nationality: `French Southern Territories Citizen`,
      },
      { isoCode: `GA`, name: `Gabon`, nationality: `Gabonese` },
      { isoCode: `GM`, name: `Gambia`, nationality: `Gambian` },
      { isoCode: `GE`, name: `Georgia`, nationality: `Georgian` },
      { isoCode: `DE`, name: `Germany`, nationality: `German` },
      { isoCode: `GH`, name: `Ghana`, nationality: `Ghanaian` },
      { isoCode: `GI`, name: `Gibraltar`, nationality: `Gibraltarian` },
      { isoCode: `GR`, name: `Greece`, nationality: `Greek` },
      { isoCode: `GL`, name: `Greenland`, nationality: `Greenlandic` },
      { isoCode: `GD`, name: `Grenada`, nationality: `Grenadian` },
      { isoCode: `GP`, name: `Guadeloupe`, nationality: `Guadeloupean` },
      { isoCode: `GU`, name: `Guam`, nationality: `Guamanian` },
      { isoCode: `GT`, name: `Guatemala`, nationality: `Guatemalan` },
      { isoCode: `GG`, name: `Guernsey`, nationality: `Guernsey Citizen` },
      { isoCode: `GN`, name: `Guinea`, nationality: `Guinean` },
      { isoCode: `GW`, name: `Guinea-Bissau`, nationality: `Guinea-Bissauan` },
      { isoCode: `GY`, name: `Guyana`, nationality: `Guyanese` },
      { isoCode: `HT`, name: `Haiti`, nationality: `Haitian` },
      {
        isoCode: `HM`,
        name: `Heard Island and Mcdonald Islands`,
        nationality: `Heard and McDonald Islander`,
      },
      { isoCode: `VA`, name: `Holy See (Vatican City State)`, nationality: `Vatican` },
      { isoCode: `HN`, name: `Honduras`, nationality: `Honduran` },
      { isoCode: `HK`, name: `Hong Kong`, nationality: `Hong Kong Citizen` },
      { isoCode: `HU`, name: `Hungary`, nationality: `Hungarian` },
      { isoCode: `IS`, name: `Iceland`, nationality: `Icelandic` },
      { isoCode: `IN`, name: `India`, nationality: `Indian` },
      { isoCode: `ID`, name: `Indonesia`, nationality: `Indonesian` },
      { isoCode: `IR`, name: `Iran, Islamic Republic Of`, nationality: `Iranian` },
      { isoCode: `IQ`, name: `Iraq`, nationality: `Iraqi` },
      { isoCode: `IE`, name: `Ireland`, nationality: `Irish` },
      { isoCode: `IM`, name: `Isle of Man`, nationality: `Manx` },
      { isoCode: `IL`, name: `Israel`, nationality: `Israeli` },
      { isoCode: `IT`, name: `Italy`, nationality: `Italian` },
      { isoCode: `JM`, name: `Jamaica`, nationality: `Jamaican` },
      { isoCode: `JP`, name: `Japan`, nationality: `Japanese` },
      { isoCode: `JE`, name: `Jersey`, nationality: `Jersey Citizen` },
      { isoCode: `JO`, name: `Jordan`, nationality: `Jordanian` },
      { isoCode: `KZ`, name: `Kazakhstan`, nationality: `Kazakhstani` },
      { isoCode: `KE`, name: `Kenya`, nationality: `Kenyan` },
      { isoCode: `KI`, name: `Kiribati`, nationality: `I-Kiribati` },
      {
        isoCode: `KP`,
        name: 'Korea, Democratic People`S Republic of',
        nationality: `North Korean`,
      },
      { isoCode: `KR`, name: `Korea, Republic of`, nationality: `South Korean` },
      { isoCode: `KW`, name: `Kuwait`, nationality: `Kuwaiti` },
      { isoCode: `KG`, name: `Kyrgyzstan`, nationality: `Kyrgyzstani` },
      { isoCode: `LA`, name: 'Lao People`S Democratic Republic', nationality: `Laotian` },
      { isoCode: `LV`, name: `Latvia`, nationality: `Latvian` },
      { isoCode: `LB`, name: `Lebanon`, nationality: `Lebanese` },
      { isoCode: `LS`, name: `Lesotho`, nationality: `Lesothan` },
      { isoCode: `LR`, name: `Liberia`, nationality: `Liberian` },
      { isoCode: `LY`, name: `Libyan Arab Jamahiriya`, nationality: `Libyan` },
      { isoCode: `LI`, name: `Liechtenstein`, nationality: `Liechtensteiner` },
      { isoCode: `LT`, name: `Lithuania`, nationality: `Lithuanian` },
      { isoCode: `LU`, name: `Luxembourg`, nationality: `Luxembourgish` },
      { isoCode: `MO`, name: `Macao`, nationality: `Macanese` },
      {
        isoCode: `MK`,
        name: `Macedonia, The Former Yugoslav Republic of`,
        nationality: `Macedonian`,
      },
      { isoCode: `MG`, name: `Madagascar`, nationality: `Malagasy` },
      { isoCode: `MW`, name: `Malawi`, nationality: `Malawian` },
      { isoCode: `MY`, name: `Malaysia`, nationality: `Malaysian` },
      { isoCode: `MV`, name: `Maldives`, nationality: `Maldivian` },
      { isoCode: `ML`, name: `Mali`, nationality: `Malian` },
      { isoCode: `MT`, name: `Malta`, nationality: `Maltese` },
      { isoCode: `MH`, name: `Marshall Islands`, nationality: `Marshallese` },
      { isoCode: `MQ`, name: `Martinique`, nationality: `Martinican` },
      { isoCode: `MR`, name: `Mauritania`, nationality: `Mauritanian` },
      { isoCode: `MU`, name: `Mauritius`, nationality: `Mauritian` },
      { isoCode: `YT`, name: `Mayotte`, nationality: `Mahoran` },
      { isoCode: `MX`, name: `Mexico`, nationality: `Mexican` },
      { isoCode: `FM`, name: `Micronesia, Federated States of`, nationality: `Micronesian` },
      { isoCode: `MD`, name: `Moldova, Republic of`, nationality: `Moldovan` },
      { isoCode: `MC`, name: `Monaco`, nationality: `Monacan` },
      { isoCode: `MN`, name: `Mongolia`, nationality: `Mongolian` },
      { isoCode: `MS`, name: `Montserrat`, nationality: `Montserratian` },
      { isoCode: `MA`, name: `Morocco`, nationality: `Moroccan` },
      { isoCode: `MZ`, name: `Mozambique`, nationality: `Mozambican` },
      { isoCode: `MM`, name: `Myanmar`, nationality: `Burmese` },
      { isoCode: `NA`, name: `Namibia`, nationality: `Namibian` },
      { isoCode: `NR`, name: `Nauru`, nationality: `Nauruan` },
      { isoCode: `NP`, name: `Nepal`, nationality: `Nepalese` },
      { isoCode: `NL`, name: `Netherlands`, nationality: `Dutch` },
      { isoCode: `AN`, name: `Netherlands Antilles`, nationality: `Netherlands Antillean` },
      { isoCode: `NC`, name: `New Caledonia`, nationality: `New Caledonian` },
      { isoCode: `NZ`, name: `New Zealand`, nationality: `New Zealand Citizen` },
      { isoCode: `NI`, name: `Nicaragua`, nationality: `Nicaraguan` },
      { isoCode: `NE`, name: `Niger`, nationality: `Nigerien` },
      { isoCode: `NG`, name: `Nigeria`, nationality: `Nigerian` },
      { isoCode: `NU`, name: `Niue`, nationality: `Niuean` },
      { isoCode: `NF`, name: `Norfolk Island`, nationality: `Norfolk Islander` },
      { isoCode: `MP`, name: `Northern Mariana Islands`, nationality: `Northern Mariana Islander` },
      { isoCode: `NO`, name: `Norway`, nationality: `Norwegian` },
      { isoCode: `OM`, name: `Oman`, nationality: `Omani` },
      { isoCode: `PK`, name: `Pakistan`, nationality: `Pakistani` },
      { isoCode: `PW`, name: `Palau`, nationality: `Palauan` },
      { isoCode: `PS`, name: `Palestinian Territory, Occupied`, nationality: `Palestinian` },
      { isoCode: `PA`, name: `Panama`, nationality: `Panamanian` },
      { isoCode: `PG`, name: `Papua New Guinea`, nationality: `Papua New Guinean` },
      { isoCode: `PY`, name: `Paraguay`, nationality: `Paraguayan` },
      { isoCode: `PE`, name: `Peru`, nationality: `Peruvian` },
      { isoCode: `PH`, name: `Philippines`, nationality: `Filipino` },
      { isoCode: `PN`, name: `Pitcairn`, nationality: `Pitcairn Islander` },
      { isoCode: `PL`, name: `Poland`, nationality: `Polish` },
      { isoCode: `PT`, name: `Portugal`, nationality: `Portuguese` },
      { isoCode: `PR`, name: `Puerto Rico`, nationality: `Puerto Rican` },
      { isoCode: `QA`, name: `Qatar`, nationality: `Qatari` },
      { isoCode: `RE`, name: `Reunion`, nationality: `Reunionese` },
      { isoCode: `RO`, name: `Romania`, nationality: `Romanian` },
      { isoCode: `RU`, name: `Russian Federation`, nationality: `Russian` },
      { isoCode: `RW`, name: `RWANDA`, nationality: `Rwandan` },
      { isoCode: `SH`, name: `Saint Helena`, nationality: `Saint Helenian` },
      { isoCode: `KN`, name: `Saint Kitts and Nevis`, nationality: `Kittitian or Nevisian` },
      { isoCode: `LC`, name: `Saint Lucia`, nationality: `Saint Lucian` },
      {
        isoCode: `PM`,
        name: `Saint Pierre and Miquelon`,
        nationality: `Saint-Pierrais or Miquelonnais`,
      },
      {
        isoCode: `VC`,
        name: `Saint Vincent and the Grenadines`,
        nationality: `Saint Vincentian or Grenadian`,
      },
      { isoCode: `WS`, name: `Samoa`, nationality: `Samoan` },
      { isoCode: `SM`, name: `San Marino`, nationality: `Sammarinese` },
      { isoCode: `ST`, name: `Sao Tome and Principe`, nationality: `Sao Tomean` },
      { isoCode: `SA`, name: `Saudi Arabia`, nationality: `Saudi Arabian` },
      { isoCode: `SN`, name: `Senegal`, nationality: `Senegalese` },
      { isoCode: `CS`, name: `Serbia and Montenegro`, nationality: `Serbian or Montenegrin` },
      { isoCode: `SC`, name: `Seychelles`, nationality: `Seychellois` },
      { isoCode: `SL`, name: `Sierra Leone`, nationality: `Sierra Leonean` },
      { isoCode: `SG`, name: `Singapore`, nationality: `Singaporean` },
      { isoCode: `SK`, name: `Slovakia`, nationality: `Slovak` },
      { isoCode: `SI`, name: `Slovenia`, nationality: `Slovenian` },
      { isoCode: `SB`, name: `Solomon Islands`, nationality: `Solomon Islander` },
      { isoCode: `SO`, name: `Somalia`, nationality: `Somali` },
      { isoCode: `ZA`, name: `South Africa`, nationality: `South African` },
      {
        isoCode: `GS`,
        name: `South Georgia and the South Sandwich Islands`,
        nationality: `South Georgia and the South Sandwich Islander`,
      },
      { isoCode: `ES`, name: `Spain`, nationality: `Spanish` },
      { isoCode: `LK`, name: `Sri Lanka`, nationality: `Sri Lankan` },
      { isoCode: `SD`, name: `Sudan`, nationality: `Sudanese` },
      { isoCode: `SR`, name: `Suriname`, nationality: `Surinamese` },
      {
        isoCode: `SJ`,
        name: `Svalbard and Jan Mayen`,
        nationality: `Svalbard and Jan Mayen Citizen`,
      },
      { isoCode: `SZ`, name: `Swaziland`, nationality: `Swazi` },
      { isoCode: `SE`, name: `Sweden`, nationality: `Swedish` },
      { isoCode: `CH`, name: `Switzerland`, nationality: `Swiss` },
      { isoCode: `SY`, name: `Syrian Arab Republic`, nationality: `Syrian` },
      { isoCode: `TW`, name: `Taiwan, Province of China`, nationality: `Taiwanese` },
      { isoCode: `TJ`, name: `Tajikistan`, nationality: `Tajikistani` },
      { isoCode: `TZ`, name: `Tanzania, United Republic of`, nationality: `Tanzanian` },
      { isoCode: `TH`, name: `Thailand`, nationality: `Thai` },
      { isoCode: `TL`, name: `Timor-Leste`, nationality: `Timorese` },
      { isoCode: `TG`, name: `Togo`, nationality: `Togolese` },
      { isoCode: `TK`, name: `Tokelau`, nationality: `Tokelauan` },
      { isoCode: `TO`, name: `Tonga`, nationality: `Tongan` },
      { isoCode: `TT`, name: `Trinidad and Tobago`, nationality: `Trinidadian or Tobagonian` },
      { isoCode: `TN`, name: `Tunisia`, nationality: `Tunisian` },
      { isoCode: `TR`, name: `Turkey`, nationality: `Turkish` },
      { isoCode: `TM`, name: `Turkmenistan`, nationality: `Turkmen` },
      { isoCode: `TC`, name: `Turks and Caicos Islands`, nationality: `Turks and Caicos Islander` },
      { isoCode: `TV`, name: `Tuvalu`, nationality: `Tuvaluan` },
      { isoCode: `UG`, name: `Uganda`, nationality: `Ugandan` },
      { isoCode: `UA`, name: `Ukraine`, nationality: `Ukrainian` },
      { isoCode: `AE`, name: `United Arab Emirates`, nationality: `Emirati` },
      { isoCode: `GB`, name: `United Kingdom`, nationality: `British` },
      { isoCode: `US`, name: `United States`, nationality: `American` },
      { isoCode: `UM`, name: `United States Minor Outlying Islands`, nationality: `American` },
      { isoCode: `UY`, name: `Uruguay`, nationality: `Uruguayan` },
      { isoCode: `UZ`, name: `Uzbekistan`, nationality: `Uzbekistani` },
      { isoCode: `VU`, name: `Vanuatu`, nationality: `Ni-Vanuatu` },
      { isoCode: `VE`, name: `Venezuela`, nationality: `Venezuelan` },
      { isoCode: `VN`, name: `Viet Nam`, nationality: `Vietnamese` },
      { isoCode: `VG`, name: `Virgin Islands, British`, nationality: `British Virgin Islander` },
      { isoCode: `VI`, name: `Virgin Islands, U.S.`, nationality: `U.S. Virgin Islander` },
      { isoCode: `WF`, name: `Wallis and Futuna`, nationality: `Wallisian or Futunan` },
      { isoCode: `EH`, name: `Western Sahara`, nationality: `Sahrawi` },
      { isoCode: `YE`, name: `Yemen`, nationality: `Yemeni` },
      { isoCode: `ZM`, name: `Zambia`, nationality: `Zambian` },
      { isoCode: `ZW`, name: `Zimbabwe`, nationality: `Zimbabwean` },
    ])
  }
}
